spring:
  jmx:
    enabled: true
  pid:
    file: logs/webtoon-api.pid
  server:
    port: 5050

client:
  daum:
    url: http://webtoon.daum.net/data/pc/webtoon/list_serialized/
    page: /webtoon/view/
  naver:
    url: https://comic.naver.com/webtoon/weekday.nhn
